exports.UNIQUE_KEY = '__UNIQUE__KEY__';

exports.JOB_STAGE_VALIDATE_PARAMS = 'VALIDATE_PARAMS';
exports.JOB_STAGE_QUICK_RUN = 'QUICK_RUN';
exports.JOB_STAGE_RUN = 'RUN';

exports.JOB_REGISTERED = 'JOB_REGISTERED';
exports.JOB_UNREGISTERED = 'JOB_UNREGISTERED';

exports.EVENT_JOB_CREATED = 'JOB_CREATED';
exports.EVENT_JOB_STARTED = 'JOB_STARTED';
exports.EVENT_JOB_FORKED = 'JOB_FORKED';
exports.EVENT_JOB_SUCCESS = 'JOB_SUCCESS';
exports.EVENT_JOB_FAILURE = 'JOB_FAILURE';
exports.EVENT_JOB_PROGRESS = 'JOB_PROGRESS';

exports.JOB_MESSAGE_STARTUP = '__JOBHUB_WORKER_STARTUP__';
exports.JOB_MESSAGE_PAYLOAD = '__JOBHUB_WORKER_PAYLOAD__';
exports.JOB_MESSAGE_SUCCESS = '__JOBHUB_WORKER_SUCCESS__';
exports.JOB_MESSAGE_ERROR = '__JOBHUB_WORKER_ERROR__';
exports.JOB_MESSAGE_PROGRESS = '__JOBHUB_WORKER_PROGRESS__';

exports.MIDDLEWARE_LOAD_JOBS = 'MIDDLEWARE_LOAD_JOBS';
exports.MIDDLEWARE_CREATE_JOB = 'MIDDLEWARE_CREATE_JOB';
exports.MIDDLEWARE_FORK_JOB_PROCESS = 'MIDDLEWARE_FORK_JOB_PROCESS';
exports.MIDDLEWARE_BUILD_FORK_ARGS = 'MIDDLEWARE_BUILD_FORK_ARGS';
exports.MIDDLEWARE_BUILD_FORK_OPTS = 'MIDDLEWARE_BUILD_FORK_OPTS';
exports.MIDDLEWARE_CREATE_WORKER_MEDIATOR = 'MIDDLEWARE_CREATE_WORKER_MEDIATOR';
